### ISSUE TITLE
Saving anything and then loading that file always leads to a crash

### ISSUE THREAD

**Issue by sonofevil** [Meowmaritus/DSAnimStudio#43]
Steps to reproduce:
1. Open any .anibnd from Dark Souls PTDE
2. "Save as" and select any of file types.
3. Open the just saved file.

Result: 
This error pops up. App is stuck on "Opening ANIBND..." Further attempts to open any other file do nothing until the app is closed.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\windows\DSModding\DSAnimStudio_v3.0.5\chr\c5210.chrbnd'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SoulsFormats.SoulsFile`1.Read(String path)
   at DSAnimStudio.GameDataManager.<>c__DisplayClass55_0.<LoadCharacter>b__0(IProgress`1 progress) in C:\Users\Green\GitHub\DSAnimStudio-Dev\DSAnimStudio\GameDataManager.cs:line 696
   at DSAnimStudio.LoadingTaskMan.<>c__DisplayClass5_0.<DoLoadingTask>b__0(IProgress`1 progress) in C:\Users\Green\GitHub\DSAnimStudio-Dev\DSAnimStudio\LoadingTaskMan.cs:line 179
   at DSAnimStudio.LoadingTaskMan.LoadingTask.<>c__DisplayClass14_1.<.ctor>b__1() in C:\Users\Green\GitHub\DSAnimStudio-Dev\DSAnimStudio\LoadingTaskMan.cs:line 56
```

Reproducible: Always.

Note that my NET version is 4.8.04084, not 4.7.2. Windows does not seem to allow uninstalling or downgrading the newer version by normal means, so I can't test if it works on 4.7.2.

**Comment by sonofevil** [comment]
Wait I just realized what the error is actually saying. I'm dumb, sorry.

Gotta have the .chrbnd in the same folder apparently.
