### ISSUE TITLE
Fatal Error encountered during background task 'File_Open':

### ISSUE THREAD

**Issue by Eizen94** [Meowmaritus/DSAnimStudio#58]
System.FormatException: Unknown DCX format.
   at SoulsFormats.DCX.Decompress(BinaryReaderEx br, Type& type) in C:\Users\Green\GitHub\DSAnimStudio\SoulsAssetPipeline\SoulsFormats\SoulsFormats\Formats\DCX.cs:line 165
   at SoulsFormats.SFUtil.GetDecompressedBR(BinaryReaderEx br, Type& compression) in C:\Users\Green\GitHub\DSAnimStudio\SoulsAssetPipeline\SoulsFormats\SoulsFormats\Util\SFUtil.cs:line 210
   at SoulsFormats.SoulsFile`1.Read(Byte[] bytes) in C:\Users\Green\GitHub\DSAnimStudio\SoulsAssetPipeline\SoulsFormats\SoulsFormats\Util\SoulsFile.cs:line 68
   at DSAnimStudio.ParamCryptoUtil.DecryptERRegulation(Byte[] bytes) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\ParamCryptoUtil.cs:line 103
   at DSAnimStudio.ParamManager.LoadParamBND(Boolean forceReload) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\ParamManager.cs:line 367
   at DSAnimStudio.GameRoot.Init(String assetPath, SoulsGames gameType, String scratchFolder, Boolean forceReload, Boolean overrideInterrootPicker) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\GameRoot.cs:line 466
   at DSAnimStudio.TaeEditor.TaeFileContainer.CheckGameVersionForTaeInterop(String filePath, String internalFilePath, Boolean isRemo) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\TaeEditor\TaeFileContainer.cs:line 404
   at DSAnimStudio.TaeEditor.TaeFileContainer.LoadFromPath(String file, String possibleFallbackPath) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\TaeEditor\TaeFileContainer.cs:line 610
   at DSAnimStudio.TaeEditor.TaeEditorScreen.LoadCurrentFile() in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\TaeEditor\TaeEditorScreen.cs:line 836
   at DSAnimStudio.TaeEditor.TaeEditorScreen.<File_Open>b__210_2(IProgress`1 progress) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\TaeEditor\TaeEditorScreen.cs:line 1892
   at DSAnimStudio.LoadingTaskMan.<>c__DisplayClass5_0.<DoLoadingTask>b__0(IProgress`1 progress) in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\LoadingTaskMan.cs:line 185
   at DSAnimStudio.LoadingTaskMan.LoadingTask.<>c__DisplayClass13_1.<.ctor>b__1() in C:\Users\Green\GitHub\DSAnimStudio\DSAnimStudioNETCore\LoadingTaskMan.cs:line 62
![Screenshot 2024-07-06 184815](https://github.com/Meowmaritus/DSAnimStudio/assets/153494374/8b618e0b-5f5a-4161-a68b-a341fb5b51ac)

**Comment by scruffy2461** [comment]
got the same issue

**Comment by varswd** [comment]
got the same issue

**Comment by AltairTheArc** [comment]
same problem, tried ver 4.9.9 and 4.9.4 both had same problem

**Comment by varswd** [comment]
The DSA version 4 seems to no longer be available, and you need to subscribe to the author on Patreon for the latest version 5 software.

**Comment by cango91** [comment]
@varswd thank you for your guidance.
Can confirm the v5.0rc3.1 version (Patreon) fixes this error for me.

**Comment by mooofin** [comment]
it's paywalled , you need the version 5 to edit . Down patching your game should work

**Comment by mooofin** [comment]
wait for the creator to make it open , hopefully soom
